### ISSUE TITLE
[feature suggestion] add placeholder for `highest_on_track_<track>`

### ISSUE THREAD

**Issue by RalphORama** [LuckPerms/placeholders#50]
I think it would be useful if placeholders for [Prefix and Suffix Stacking](https://luckperms.net/wiki/Prefix-&-Suffix-Stacking#how-do-i-add-other-elements) were also available through PAPI etc.

My use case is this: VentureChat supports JSON hover / click events, and I would like to set up prefixes from individual tracks to have different hover elements. My current `meta-formatting` from LuckPerms looks like this:

<details>

<summary>`meta-formatting` from `config.yml`</summary>

```yml
meta-formatting:
  prefix:
    format:
      - "highest_on_track_staff"
      - "highest_on_track_vip"
      - "highest_on_track_patron"
      - "highest_on_track_discord-booster"
      - "highest_own"
    duplicates: none
    start-spacer: ""
    middle-spacer: ""
    end-spacer: "&r &7|&r "
  suffix:
    format:
      - "highest_on_track_staff"
      - "highest_on_track_vip"
      - "highest_on_track_patron"
      - "highest_on_track_discord-booster"
      - "highest_own"
    duplicates: none
    start-spacer: ""
    middle-spacer: " "
    end-spacer: ""
```

</details>

And my VentureChat config like this:

<details>

<summary>`config.yml` from VentureChat</summary>

```yml
jsonformatting:
  Default: 
    json_attributes:
      luckperms_prefix:
        hover_text:
        - '&cI am default!'
        click_action: 'run_command'
        click_text: '/help'

# ...

channels:
  Global:
    # ...
    format: '{luckperms_prefix}{player_displayname}{luckperms_suffix}:'
```

</details>

I would like the ability to break out `highest_on_track_<track>` so I could do the meta formatting in the VentureChat config itself and add a section in `jsonformatting` to have different hover text for every track prefix. Then I could, for example, have something like:

```yml
jsonformatting:
  Default: 
    json_attributes:
      luckperms_highest_on_track_vip:
        hover_text:
        - '&cVIP member! &eClick to learn how to buy this rank.'
        click_action: 'run_command'
        click_text: '/donate'

channels:
  Global:
    # ...
    format: '{luckperms_highest_on_track_vip}{player_displayname}{luckperms_suffix}:'
```
